### ISSUE TITLE
Will this be maintained?

### ISSUE THREAD

**Issue by binaryben** [Log1x/bulma.styl#6]
I'm always sorry to ask this of open source project maintainers, but I'm wondering if there is any plan to keep this updated with future revisions of Bulma, or if it was maybe a one-shot publish to Github? 😄 ❤️

**Comment by Log1x** [comment]
I will try to update it soon. The agency I'm now working for only lets me use SASS, so I haven't been maintaining this as much as I'd hope despite preferring Stylus + PostCSS.

Prior to that, I was updating it almost daily and it was never meant to be a one-shot publish.

I had a few people say they were going to help maintain it but they never opened a PR.

I'll try to do it this week/weekend or by mid of next week as I do have a freelance project that I'm back on that originally used this, so I'd like to update this instead of converting it to SASS for future maintainability.

Otherwise, any help is appreciated. It'd be easier if jgthms' wrote better commit messages. It can be rather cumbersome finding actual Bulma-related changes as he tends to plop them in randomly when doing the documentation and finding something doesn't work how he wants it too.

**Comment by binaryben** [comment]
Yeh, that is precisely why I was sorry to ask. I can't contribute to the project either unfortunately, and I don't want to put any pressure on you. :)

Thank you for the prompt reply regardless! Glad to hear an update may eventually come. Don't rush on my account of course.

**Comment by Log1x** [comment]
I decided to convert the site I was working on back over to SASS with a PostCSS workflow for easier maintainability so I will no longer have any plans to keep this up to date. Any forks or PR's are much appreciated, though. If someone was willing to catch it up I could help update it where possible-- but otherwise, I can't afford the time to sift through every Bulma commit by hand looking for potential changes to core that aren't docs-related. Like I said above, this had to be done carefully as a lot of subtle changes to Bulma are intertwined in completely un-related commits usually during documentation updates when jgthms stumbles upon something that isn't sitting well with him at the time.
